[build]
  base = "client"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://localhost:3000"
  NEXT_PUBLIC_APP_BASE_URL = "http://localhost:3000"

[[plugins]]
  package = "@netlify/plugin-nextjs"